<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><style>
@page{margin:18px}body{font-family:DejaVu Sans,sans-serif;font-size:8px;color:#172033}h1{font-size:16px;margin:4px 0}.meta{margin-bottom:12px}.meta div{margin:2px 0}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccd3dd;padding:4px}th{background:#0b1739;color:#fff;text-align:left}.money{text-align:right;white-space:nowrap}.voided{color:#777;background:#eee}.totals{font-weight:bold;background:#eaf1ff}.categories{margin-top:14px}.categories td{width:25%}
</style></head><body>
<div class="meta"><h1>{{ $direction->value === 'PURCHASE' ? 'Libro de Compras' : 'Libro de Ventas' }}</h1><div><strong>Empresa:</strong> {{ $company->name }}</div><div><strong>NIT:</strong> {{ $company->tax_id }}</div><div><strong>Período:</strong> {{ $report['periodDescription'] }}</div><div><strong>Generado:</strong> {{ $generatedAt->format('d/m/Y H:i:s') }} por {{ $user->name }}</div></div>
<table><thead><tr><th>Fecha</th><th>Tipo</th><th>Serie / Número</th><th>NIT</th><th>Tercero</th><th>Categoría</th><th>Base</th><th>Exento</th><th>IVA</th><th>Otros</th><th>Total</th><th>Estado</th></tr></thead><tbody>
@foreach($report['documents'] as $document)<tr class="{{ $document->status->value==='VOIDED'?'voided':'' }}"><td>{{ $document->document_date->format('d/m/Y') }}</td><td>{{ $document->document_type->label() }}</td><td>{{ $document->series }} / {{ $document->document_number }}</td><td>{{ $document->third_party_tax_id }}</td><td>{{ $document->third_party_name }}</td><td>{{ $document->tax_category->label() }}</td>@foreach(['taxable_amount','exempt_amount','vat_amount','other_taxes_amount','total_amount'] as $field)<td class="money">{{ $document->document_type->value==='CREDIT_NOTE'?'- ':'' }}Q {{ number_format((float)$document->{$field},2) }}</td>@endforeach<td>{{ $document->status->label() }}</td></tr>@endforeach
<tr class="totals"><td colspan="6">Totales de documentos activos</td><td class="money">Q {{ number_format((float)$report['totals']['taxable_amount'],2) }}</td><td class="money">Q {{ number_format((float)$report['totals']['exempt_amount'],2) }}</td><td class="money">Q {{ number_format((float)$report['totals']['vat_amount'],2) }}</td><td class="money">Q {{ number_format((float)$report['totals']['other_taxes_amount'],2) }}</td><td class="money">Q {{ number_format((float)$report['totals']['total_amount'],2) }}</td><td></td></tr>
</tbody></table>
@if($direction->value === 'PURCHASE')<table class="categories"><tr>@foreach($report['categoryTotals'] as $category)<td><strong>{{ $category['label'] }}</strong><br>Q {{ number_format((float)$category['total_amount'],2) }} · {{ $category['count'] }} docs.</td>@endforeach</tr></table>@endif
</body></html>
