<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><style>
@page{margin:20px 20px 28px}body{font-family:DejaVu Sans,sans-serif;font-size:8px;color:#172033}.footer{position:fixed;bottom:-18px;left:0;right:0;text-align:center;color:#667}.footer .page:after{content:counter(page)}h1{font-size:18px;margin:5px 0}.company{font-size:15px;font-weight:bold;text-transform:uppercase}.header{border-bottom:2px solid #0b1739;padding-bottom:8px}.meta{width:100%;border-collapse:collapse}.meta td{border:0;padding:2px 12px 2px 0}.notice{background:#fff3cd;border:1px solid #ffecb5;padding:7px;margin:9px 0;font-weight:bold}.grid{width:100%;border-collapse:collapse;margin:8px 0}.grid th,.grid td{border:1px solid #ccd3dd;padding:4px}.grid th{background:#0b1739;color:white}.money{text-align:right}.section{font-size:12px;color:#0b1739;margin:10px 0 4px}.excluded{background:#f8d7da}.included{background:#eef7ee}
</style></head><body>
<div class="footer">Página <span class="page"></span></div>
<div class="header"><div class="company">{{ $company->legal_name ?: $company->name }}</div><div><strong>NIT:</strong> {{ $company->tax_id }}</div><h1>DECLARACIÓN DE IVA{{ $declaration->status->value !== 'FILED' ? ' - BORRADOR' : '' }}</h1><table class="meta"><tr><td><strong>Período:</strong> {{ $declaration->accountingPeriod->name }}<br><strong>Del:</strong> {{ $declaration->accountingPeriod->start_date->format('d/m/Y') }} al {{ $declaration->accountingPeriod->end_date->format('d/m/Y') }}</td><td><strong>Régimen:</strong> IVA General<br><strong>Estado:</strong> {{ $declaration->status->label() }}</td><td><strong>Generado:</strong> {{ $generatedAt->format('d/m/Y H:i:s') }}<br><strong>por:</strong> {{ $user->name }}</td></tr></table></div>
@if($declaration->status->value !== 'FILED')<div class="notice">BORRADOR PARA REVISIÓN. NO CONSTITUYE CONSTANCIA DE PRESENTACIÓN ANTE SAT.</div>@endif
<div class="section">Resumen de ventas y compras</div><table class="grid"><thead><tr><th>Concepto</th><th>Ventas</th><th>Compras</th></tr></thead><tbody>
@foreach(['taxable_amount'=>'Gravado','exempt_amount'=>'Exento','non_taxable_amount'=>'No afecto','vat_amount'=>'IVA','other_taxes_amount'=>'Otros impuestos'] as $field=>$label)<tr><td>{{ $label }}</td><td class="money">Q {{ number_format((float)$declaration->{'sales_'.$field},2) }}</td><td class="money">Q {{ number_format((float)$declaration->{'purchase_'.$field},2) }}</td></tr>@endforeach
<tr><td>IVA acreditable / no acreditable</td><td>—</td><td class="money">Q {{ number_format((float)$declaration->purchase_creditable_vat_amount,2) }} / Q {{ number_format((float)$declaration->purchase_non_creditable_vat_amount,2) }}</td></tr></tbody></table>
<div class="section">Determinación</div><table class="grid"><tr><th>Débito fiscal</th><th>Crédito fiscal</th><th>Saldo anterior</th><th>Retenciones</th><th>Ajustes débito</th><th>Ajustes crédito</th><th>IVA por pagar</th><th>Crédito siguiente</th></tr><tr>@foreach(['net_vat_debit','net_vat_credit','previous_credit_balance','vat_withholdings','manual_debit_adjustments','manual_credit_adjustments','vat_payable','credit_balance'] as $field)<td class="money">Q {{ number_format((float)$declaration->{$field},2) }}</td>@endforeach</tr></table>
@foreach([true=>'Documentos incluidos',false=>'Documentos excluidos'] as $included=>$heading)<div class="section">{{ $heading }} ({{ $declaration->documents->where('included',(bool)$included)->count() }})</div><table class="grid"><thead><tr><th>Fecha</th><th>Dirección</th><th>Documento</th><th>Tercero</th><th>Revisión</th><th>Fiscal</th><th>IVA</th><th>Total</th><th>Motivo / advertencia</th></tr></thead><tbody>@forelse($declaration->documents->where('included',(bool)$included) as $snapshot)@php($source=$snapshot->source_snapshot??[])<tr class="{{ $snapshot->included?'included':'excluded' }}"><td>{{ $source['document_date']??'—' }}</td><td>{{ $snapshot->direction->label() }}</td><td>{{ $snapshot->document_type->label() }} {{ $source['series']??'' }} {{ $source['document_number']??'' }}</td><td>{{ $source['third_party_name']??'—' }}</td><td>{{ $snapshot->review_status }}</td><td>{{ $snapshot->fiscal_status->value }}</td><td class="money">Q {{ number_format((float)$snapshot->vat_amount,2) }}</td><td class="money">Q {{ number_format((float)$snapshot->total_amount,2) }}</td><td>{{ $snapshot->exclusion_reason??'—' }}</td></tr>@empty<tr><td colspan="9">Sin documentos.</td></tr>@endforelse</tbody></table>@endforeach
</body></html>
