@extends('layouts.app')
@section('title', 'Bandeja de revisión FEL')
@section('content')
@php($labels=['PURCHASE'=>'Compra','SALE'=>'Venta','UNKNOWN'=>'Desconocida','GENERAL_PURCHASE'=>'Compra general','GENERAL_SALE'=>'Venta general','FUEL'=>'Combustible','LODGING'=>'Hospedaje','UNCLASSIFIED'=>'Sin clasificar','PENDING'=>'Pendiente','OBSERVED'=>'Observado','APPROVED'=>'Aprobado','REJECTED'=>'Rechazado','ACTIVE'=>'Activo','VOIDED'=>'Anulado','FULL_DETAIL'=>'Detalle completo','SUMMARY'=>'Solo resumen'])
<x-page-header title="Bandeja de revisión FEL" subtitle="Documentos pendientes de decisión humana · Empresa activa: {{ $activeCompanyName }}" icon="bi-inbox"><x-slot:actions><x-action-button :href="route('fel-imports.create')" icon="bi-cloud-arrow-up">Importar documentos</x-action-button><x-action-button :href="route('fel.reclassification.index')" icon="bi-arrow-repeat" variant="outline-primary">Reclasificar documentos FEL</x-action-button></x-slot:actions></x-page-header>
<div class="card shadow-sm mb-4"><div class="card-body"><form class="row g-2">
    <div class="col-md-2"><label class="form-label">Desde</label><input type="date" name="from" value="{{ request('from') }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Hasta</label><input type="date" name="to" value="{{ request('to') }}" class="form-control"></div>
    <div class="col-md-2"><label class="form-label">Operación</label><select name="operation_type" class="form-select"><option value="">Todas</option>@foreach($operationTypes as $item)<option value="{{ $item->value }}" @selected(request('operation_type')===$item->value)>{{ $labels[$item->value]??$item->value }}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label">Clasificación</label><select name="classification" class="form-select"><option value="">Todas</option>@foreach($classifications as $item)<option value="{{ $item->value }}" @selected(request('classification')===$item->value)>{{ $labels[$item->value]??$item->value }}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label">Estado interno</label><select name="status" class="form-select"><option value="">Todos</option>@foreach($statuses as $item)<option value="{{ $item->value }}" @selected(request('status')===$item->value)>{{ $labels[$item->value]??$item->value }}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label">Estado fiscal</label><select name="fiscal_status" class="form-select"><option value="">Todos</option>@foreach($fiscalStatuses as $item)<option value="{{ $item->value }}" @selected(request('fiscal_status')===$item->value)>{{ $labels[$item->value]??$item->value }}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label">Origen</label><select name="source_type" class="form-select"><option value="">Todos</option>@foreach($sourceTypes as $item)<option value="{{ $item->value }}" @selected(request('source_type')===$item->value)>{{ $item->value }}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label">Nivel</label><select name="data_level" class="form-select"><option value="">Todos</option>@foreach($dataLevels as $item)<option value="{{ $item->value }}" @selected(request('data_level')===$item->value)>{{ $labels[$item->value]??$item->value }}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label">Tipo DTE</label><input name="dte_type" value="{{ request('dte_type') }}" class="form-control"></div><div class="col-md-2"><label class="form-label">UUID</label><input name="uuid" value="{{ request('uuid') }}" class="form-control"></div><div class="col-md-2"><label class="form-label">NIT</label><input name="nit" value="{{ request('nit') }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Nombre</label><input name="name" value="{{ request('name') }}" class="form-control"></div>
    <div class="col-12 d-flex gap-2"><button class="btn btn-primary">Aplicar filtros</button><a href="{{ route('fel-documents.index') }}" class="btn btn-outline-secondary">Limpiar</a></div>
</form></div></div>
<x-table-container><table class="table table-hover align-middle mb-0 small"><thead><tr><th>Fecha</th><th>DTE / UUID</th><th>Operación</th><th>Emisor / receptor</th><th>Clasificación</th><th>Origen</th><th>IVA</th><th>Otros</th><th>Total</th><th>Estados</th><th></th></tr></thead><tbody>@forelse($documents as $document)<tr><td>{{ $document->issued_at->format('d/m/Y') }}</td><td><strong>{{ $document->dte_type }}</strong><div class="font-monospace text-muted">{{ Str::limit($document->authorization_uuid,22) }}</div></td><td><span class="badge text-bg-info">{{ $labels[$document->operation_type->value] }}</span></td><td><div>{{ $document->issuer_name }}</div><small class="text-muted">a {{ $document->receiver_name }}</small></td><td><span class="badge text-bg-{{ $document->classification->value==='FUEL'?'warning':'light' }}">{{ $labels[$document->classification->value] }}</span>@if($document->requires_tax_review)<div class="text-warning"><i class="bi bi-exclamation-triangle"></i> Revisión fiscal</div>@endif</td><td>{{ $document->source_type->value }}<br><small>{{ $labels[$document->data_level->value] }}</small></td><td>{{ number_format((float)$document->tax_total,2) }}</td><td>{{ number_format((float)$document->other_tax_total,2) }}</td><td>{{ $document->currency }} {{ number_format((float)$document->grand_total,2) }}</td><td><span class="badge text-bg-secondary">{{ $labels[$document->fiscal_status->value]??$document->fiscal_status->value }}</span><br><span class="badge text-bg-primary mt-1">{{ $labels[$document->status->value] }}</span></td><td><a href="{{ route('fel-documents.show',$document) }}" class="btn btn-sm btn-outline-primary">Revisar</a></td></tr>@empty<tr><td colspan="11"><x-empty-state title="Sin documentos" message="No hay documentos que coincidan con los filtros." /></td></tr>@endforelse</tbody></table></x-table-container><div class="mt-3">{{ $documents->links() }}</div>
@endsection
