@extends('layouts.app')
@section('title', 'Documento FEL')
@section('content')
@php($labels=['PURCHASE'=>'Compra','SALE'=>'Venta','UNKNOWN'=>'Desconocida','GENERAL_PURCHASE'=>'Compra general','GENERAL_SALE'=>'Venta general','FUEL'=>'Combustible','LODGING'=>'Hospedaje','UNCLASSIFIED'=>'Sin clasificar','PENDING'=>'Pendiente','OBSERVED'=>'Observado','APPROVED'=>'Aprobado','REJECTED'=>'Rechazado','ACTIVE'=>'Activo','VOIDED'=>'Anulado','UNKNOWN'=>'Desconocido','FULL_DETAIL'=>'Detalle completo','SUMMARY'=>'Solo resumen'])
<x-page-header title="Documento {{ $document->dte_type }}" subtitle="{{ $document->authorization_uuid }}" icon="bi-file-earmark-text"><x-slot:actions><x-action-button :href="route('fel-documents.index')" variant="outline-secondary" icon="bi-arrow-left">Bandeja</x-action-button>@if($document->xml_path)<x-action-button :href="route('fel-documents.xml',$document)" variant="outline-primary" icon="bi-download">XML original</x-action-button>@endif</x-slot:actions></x-page-header>
@if($document->requires_tax_review || $document->fiscal_status->value==='VOIDED' || $document->operation_type->value==='UNKNOWN')<div class="alert alert-warning"><i class="bi bi-exclamation-triangle me-2"></i>Este documento requiere atención especial. La decisión debe ser explícita y no generará una póliza.</div>@endif
<div class="row g-4"><div class="col-lg-8">
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Encabezado</strong></div><div class="card-body row g-3">@foreach(['Serie'=>$document->series,'Número'=>$document->document_number,'Fecha'=>$document->issued_at->format('d/m/Y H:i'),'Estado fiscal'=>$labels[$document->fiscal_status->value]??$document->fiscal_status->value,'Estado interno'=>$labels[$document->status->value],'Origen'=>$document->source_type->value,'Nivel'=>$labels[$document->data_level->value]] as $label=>$value)<div class="col-md-4"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $value ?: '—' }}</strong></div>@endforeach</div></div>
<div class="row g-4 mb-4"><div class="col-md-6"><div class="card h-100 shadow-sm"><div class="card-header"><strong>Emisor</strong></div><div class="card-body"><strong>{{ $document->issuer_name ?: '—' }}</strong><p class="mb-1">NIT: {{ $document->issuer_tax_id ?: '—' }}</p><p class="mb-1">{{ $document->issuer_commercial_name }}</p><p class="text-muted mb-0">{{ $document->issuer_address }}</p></div></div></div><div class="col-md-6"><div class="card h-100 shadow-sm"><div class="card-header"><strong>Receptor</strong></div><div class="card-body"><strong>{{ $document->receiver_name ?: '—' }}</strong><p class="mb-1">ID/NIT: {{ $document->receiver_tax_id ?: '—' }}</p><p class="text-muted mb-0">{{ $document->receiver_address }}</p></div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Totales</strong></div><div class="card-body row g-3">@foreach(['Subtotal'=>'subtotal','Descuentos'=>'discount_total','Monto gravable'=>'taxable_total','IVA'=>'tax_total','Otros impuestos'=>'other_tax_total','Gran total'=>'grand_total'] as $label=>$field)<div class="col-6 col-md-4"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $document->currency }} {{ number_format((float)$document->$field,2) }}</strong></div>@endforeach</div></div>
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Ítems</strong></div>@if($document->data_level->value==='SUMMARY')<div class="card-body text-muted">Este documento fue importado como resumen y no contiene detalle de productos.</div>@else<div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Línea</th><th>Tipo</th><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Descuento</th><th>Impuestos</th><th>Total</th></tr></thead><tbody>@foreach($document->items as $item)<tr><td>{{ $item->line_number }}</td><td>{{ $item->goods_or_service }}</td><td>{{ $item->description }}</td><td>{{ $item->quantity }}</td><td>{{ number_format((float)$item->unit_price,2) }}</td><td>{{ number_format((float)$item->discount,2) }}</td><td>{{ number_format((float)$item->tax_amount,2) }}</td><td>{{ number_format((float)$item->total,2) }}</td></tr>@endforeach</tbody></table></div>@endif</div>
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Impuestos dinámicos</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Impuesto</th><th>Nivel</th><th>Gravable</th><th>Monto</th></tr></thead><tbody>@forelse($document->taxes as $tax)<tr><td>{{ $tax->tax_name }}</td><td>{{ $tax->source_level->value }}</td><td>{{ number_format((float)$tax->taxable_amount,2) }}</td><td>{{ number_format((float)$tax->tax_amount,2) }}</td></tr>@empty<tr><td colspan="4" class="text-muted">Sin impuestos informados.</td></tr>@endforelse</tbody></table></div></div>
@if($document->complements)<div class="card shadow-sm mb-4"><div class="card-header"><strong>Complementos</strong></div><div class="card-body"><pre class="small bg-light p-3 rounded mb-0">{{ json_encode($document->complements, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></div></div>@endif
</div><div class="col-lg-4">
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Clasificación</strong></div><div class="card-body"><p><span class="badge text-bg-info">{{ $labels[$document->operation_type->value] }}</span> <span class="badge text-bg-warning">{{ $labels[$document->classification->value] }}</span></p><p class="mb-0">{{ $document->requires_tax_review ? 'Requiere revisión fiscal' : 'Sin alerta fiscal automática' }}</p></div></div>
@php($sync = $document->fiscalDocument?->source_metadata ?? data_get($document->metadata, 'fiscal_sync', []))
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Sincronización fiscal</strong></div><div class="card-body">
<p><span class="badge text-bg-{{ $document->fiscalDocument ? 'success' : 'warning' }}">{{ data_get($sync, 'synchronization_action', data_get($sync, 'action', $document->fiscalDocument ? 'SINCRONIZADO' : 'PENDIENTE')) }}</span></p>
@if($document->fiscalDocument)
<p class="mb-1">Libro: <strong>{{ $document->fiscalDocument->direction->label() }}</strong></p>
<p class="mb-1">Categoría: {{ $document->fiscalDocument->tax_category->label() }}</p>
<p class="mb-2">Estado: {{ $document->fiscalDocument->status->label() }}</p>
<a class="btn btn-sm btn-outline-primary" href="{{ route($document->fiscalDocument->direction->value === 'PURCHASE' ? 'fiscal-purchases.show' : 'fiscal-sales.show', $document->fiscalDocument) }}">Ver documento fiscal</a>
@else<p class="text-muted">El documento aún no ha podido incorporarse a un libro fiscal.</p>@endif
@if(data_get($sync, 'synchronized_at'))<small class="d-block text-muted mt-2">Última sincronización: {{ \Illuminate\Support\Carbon::parse(data_get($sync, 'synchronized_at'))->format('d/m/Y H:i') }}</small>@endif
@foreach(data_get($sync, 'warnings', []) as $warning)<div class="alert alert-warning small py-2 mt-2 mb-0">{{ $warning }}</div>@endforeach
@foreach(data_get($sync, 'errors', []) as $error)<div class="alert alert-danger small py-2 mt-2 mb-0">{{ $error }}</div>@endforeach
</div></div>
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Certificación</strong></div><div class="card-body"><p><strong>{{ $document->certifier_name ?: '—' }}</strong></p><p>NIT: {{ $document->certifier_tax_id ?: '—' }}</p><p>Fecha: {{ $document->certified_at?->format('d/m/Y H:i') ?: '—' }}</p><p class="mb-0">Firmas detectadas: {{ $document->signature_count }}</p></div></div>
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Revisión humana</strong></div><div class="card-body"><form method="POST" action="{{ route('fel-documents.approve',$document) }}" class="mb-3">@csrf<button class="btn btn-success w-100" onclick="return confirm('Aprobar sin crear póliza contable?')"><i class="bi bi-check-lg"></i> Aprobar</button></form><form method="POST" action="{{ route('fel-documents.observe',$document) }}" class="mb-3">@csrf<label class="form-label">Observación</label><textarea name="observation" required maxlength="2000" class="form-control mb-2">{{ old('observation',$document->observation) }}</textarea><button class="btn btn-warning w-100">Observar</button></form><form method="POST" action="{{ route('fel-documents.reject',$document) }}">@csrf<label class="form-label">Motivo de rechazo</label><textarea name="rejection_reason" required maxlength="2000" class="form-control mb-2">{{ old('rejection_reason',$document->rejection_reason) }}</textarea><button class="btn btn-danger w-100">Rechazar</button></form></div></div>
<div class="card shadow-sm"><div class="card-header"><strong>Auditoría</strong></div><div class="card-body small"><p>Importado por: {{ $document->importedBy->name }}</p><p>Fecha: {{ $document->created_at->format('d/m/Y H:i') }}</p><p>Lote: #{{ $document->fel_import_batch_id }}</p><p>Revisado por: {{ $document->reviewedBy?->name ?: '—' }}</p><p class="mb-0">Póliza contable: <strong>No generada</strong></p></div></div>
</div></div>
@endsection
