@php($moneyFields=['taxable_amount'=>'Base imponible','exempt_amount'=>'Monto exento','non_taxable_amount'=>'Monto no afecto','vat_amount'=>'IVA','other_taxes_amount'=>'Otros impuestos','total_amount'=>'Total'])
<div class="row g-3">
    <div class="col-md-3"><label class="form-label">Fecha</label><input type="date" name="document_date" value="{{ old('document_date', $document->document_date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" class="form-control @error('document_date') is-invalid @enderror" required>@error('document_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Período contable</label><select name="accounting_period_id" class="form-select @error('accounting_period_id') is-invalid @enderror"><option value="">Sin asociar</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(old('accounting_period_id',$document->accounting_period_id)==$period->id)>{{ $period->name }} · {{ $period->status->label() }}</option>@endforeach</select>@error('accounting_period_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">Tipo de documento</label><select name="document_type" class="form-select @error('document_type') is-invalid @enderror" required>@foreach($types as $type)<option value="{{ $type->value }}" @selected(old('document_type',$document->document_type?->value ?? 'INVOICE')===$type->value)>{{ $type->label() }}</option>@endforeach</select>@error('document_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-2"><label class="form-label">Categoría fiscal</label><select name="tax_category" class="form-select @error('tax_category') is-invalid @enderror" required>@foreach($categories as $category)<option value="{{ $category->value }}" @selected(old('tax_category',$document->tax_category?->value ?? 'GOODS')===$category->value)>{{ $category->label() }}</option>@endforeach</select>@error('tax_category')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-2"><label class="form-label">Serie</label><input name="series" value="{{ old('series',$document->series) }}" class="form-control @error('series') is-invalid @enderror">@error('series')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">Número</label><input name="document_number" value="{{ old('document_number',$document->document_number) }}" class="form-control @error('document_number') is-invalid @enderror">@error('document_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-7"><label class="form-label">UUID FEL</label><input name="authorization_uuid" value="{{ old('authorization_uuid',$document->authorization_uuid) }}" class="form-control font-monospace @error('authorization_uuid') is-invalid @enderror">@error('authorization_uuid')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">NIT del {{ strtolower($thirdPartyLabel) }}</label><input name="third_party_tax_id" value="{{ old('third_party_tax_id',$document->third_party_tax_id) }}" class="form-control @error('third_party_tax_id') is-invalid @enderror">@error('third_party_tax_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-5"><label class="form-label">Nombre del {{ strtolower($thirdPartyLabel) }}</label><input name="third_party_name" value="{{ old('third_party_name',$document->third_party_name) }}" class="form-control @error('third_party_name') is-invalid @enderror" required>@error('third_party_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Dirección</label><input name="third_party_address" value="{{ old('third_party_address',$document->third_party_address) }}" class="form-control @error('third_party_address') is-invalid @enderror">@error('third_party_address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <input type="hidden" name="currency" value="{{ old('currency',$document->currency ?: 'GTQ') }}"><input type="hidden" name="exchange_rate" value="{{ old('exchange_rate',$document->exchange_rate ?: '1.000000') }}">
    @foreach($moneyFields as $field=>$label)<div class="col-6 col-md-2"><label class="form-label">{{ $label }}</label><div class="input-group"><span class="input-group-text">Q</span><input type="number" step="0.01" min="0" name="{{ $field }}" value="{{ old($field,$document->{$field} ?? '0.00') }}" class="form-control @error($field) is-invalid @enderror" required>@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>@endforeach
    @if($direction->value === 'PURCHASE')
        <div class="col-md-3"><div class="form-check mt-4"><input type="checkbox" name="grants_tax_credit" value="1" class="form-check-input" id="grantsTaxCredit" @checked(old('grants_tax_credit',$document->grants_tax_credit))><label class="form-check-label" for="grantsTaxCredit">Genera crédito fiscal</label></div>@error('grants_tax_credit')<div class="text-danger small">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><div class="form-check mt-4"><input type="checkbox" name="is_small_taxpayer" value="1" class="form-check-input" id="smallTaxpayer" @checked(old('is_small_taxpayer',$document->is_small_taxpayer))><label class="form-check-label" for="smallTaxpayer">Es pequeño contribuyente</label></div>@error('is_small_taxpayer')<div class="text-danger small">{{ $message }}</div>@enderror</div>
    @endif
    <div class="col-md-6"><label class="form-label">Póliza contable asociada <span class="text-muted">(opcional)</span></label><select name="journal_entry_id" class="form-select @error('journal_entry_id') is-invalid @enderror"><option value="">Sin asociar</option>@foreach($journalEntries as $entry)<option value="{{ $entry->id }}" @selected(old('journal_entry_id',$document->journal_entry_id)==$entry->id)>#{{ $entry->number ?: 'Borrador' }} · {{ $entry->entry_date->format('d/m/Y') }} · {{ Str::limit($entry->description,45) }}</option>@endforeach</select>@error('journal_entry_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label">Observaciones</label><textarea name="notes" rows="3" class="form-control @error('notes') is-invalid @enderror">{{ old('notes',$document->notes) }}</textarea>@error('notes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="alert alert-info mt-4 mb-0"><i class="bi bi-info-circle me-1"></i>El total puede diferir hasta Q0.02 por redondeo. Las notas de crédito se restan automáticamente en el libro; registra siempre importes positivos.</div>
