@extends('layouts.app')
@section('title', 'Vista previa de IVA')
@section('content')
<x-page-header title="Vista previa de Declaración de IVA" subtitle="Cálculo desde los libros fiscales; todavía no constituye una presentación" icon="bi-calculator">
    <x-slot:actions>@if($existing)<a href="{{ route('vat-declarations.export.pdf',$existing) }}" class="btn btn-outline-danger">Exportar PDF</a><a href="{{ route('vat-declarations.export.excel',$existing) }}" class="btn btn-outline-success">Exportar Excel</a>@endif<a href="{{ request()->fullUrl() }}" class="btn btn-outline-primary"><i class="bi bi-arrow-repeat"></i> Recalcular desde libros</a><a href="{{ route('vat-declarations.index') }}" class="btn btn-outline-secondary">Volver</a></x-slot:actions>
</x-page-header>

<div class="card border-primary-subtle mb-4"><div class="card-body row g-3"><div class="col-md-3"><small class="text-muted">Empresa</small><div class="fw-semibold">{{ $company->legal_name ?: $company->name }}</div><div>NIT {{ $company->tax_id }}</div></div><div class="col-md-3"><small class="text-muted">Período</small><div class="fw-semibold">{{ $period->name }}</div><div>{{ $period->start_date->format('d/m/Y') }} al {{ $period->end_date->format('d/m/Y') }}</div></div><div class="col-md-3"><small class="text-muted">Régimen</small><div class="fw-semibold">IVA General</div></div><div class="col-md-3"><small class="text-muted">Estado</small><div class="fw-semibold">Borrador sin guardar</div></div></div></div>

<div class="row g-3 mb-4">@foreach(['Incluidos'=>'included','Observados'=>'observed','Rechazados'=>'rejected','Anulados'=>'voided','Datos incompletos'=>'incomplete','Sin decisión de crédito'=>'credit_undefined','Sin período'=>'without_period'] as $label=>$key)<div class="col-6 col-lg"><div class="card h-100"><div class="card-body"><small class="text-muted">{{ $label }}</small><div class="fs-4 fw-semibold">{{ $calculation['counters'][$key] }}</div></div></div></div>@endforeach</div>

@if($calculation['warnings'])<div class="alert alert-warning"><h2 class="h6">Advertencias del cálculo</h2><ul class="mb-0">@foreach($calculation['warnings'] as $warning)<li><a href="{{ route(($warning['direction']==='PURCHASE'?'fiscal-purchases':'fiscal-sales').'.show',$warning['fiscal_document_id']) }}">Documento #{{ $warning['fiscal_document_id'] }}</a>: {{ $warning['message'] }}</li>@endforeach</ul></div>@endif

<div class="row g-4 mb-4"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h2 class="h6 mb-0">Ventas</h2></div><div class="card-body">@foreach(['sales_taxable_amount'=>'Ventas gravadas','sales_exempt_amount'=>'Ventas exentas','sales_non_taxable_amount'=>'Ventas no afectas','sales_vat_amount'=>'IVA débito','sales_other_taxes_amount'=>'Otros impuestos'] as $key=>$label)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $label }}</span><strong>Q {{ number_format((float)$calculation['totals'][$key],2) }}</strong></div>@endforeach<div class="small text-muted mt-3">Notas de crédito: {{ $calculation['includedDocuments']->where('direction','SALE')->where('document_type','CREDIT_NOTE')->count() }} · Notas de débito: {{ $calculation['includedDocuments']->where('direction','SALE')->where('document_type','DEBIT_NOTE')->count() }}</div></div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h2 class="h6 mb-0">Compras</h2></div><div class="card-body">@foreach(['purchase_taxable_amount'=>'Compras gravadas','purchase_exempt_amount'=>'Compras exentas','purchase_non_taxable_amount'=>'Compras no afectas','purchase_vat_amount'=>'IVA total','purchase_creditable_vat_amount'=>'IVA acreditable','purchase_non_creditable_vat_amount'=>'IVA no acreditable','purchase_other_taxes_amount'=>'Otros impuestos'] as $key=>$label)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $label }}</span><strong>Q {{ number_format((float)$calculation['totals'][$key],2) }}</strong></div>@endforeach<div class="small text-muted mt-3">Notas de crédito: {{ $calculation['includedDocuments']->where('direction','PURCHASE')->where('document_type','CREDIT_NOTE')->count() }} · Notas de débito: {{ $calculation['includedDocuments']->where('direction','PURCHASE')->where('document_type','DEBIT_NOTE')->count() }}</div></div></div></div></div>

<form method="POST" action="{{ route('vat-declarations.store') }}" class="card mb-4">@csrf<input type="hidden" name="accounting_period_id" value="{{ $period->id }}"><div class="card-header"><h2 class="h6 mb-0">Saldos y ajustes manuales</h2></div><div class="card-body"><div class="row g-3">@foreach(['previous_credit_balance'=>'Saldo de crédito anterior','vat_withholdings'=>'Retenciones de IVA','vat_perceptions'=>'Percepciones de IVA','manual_debit_adjustments'=>'Ajustes manuales de débito','manual_credit_adjustments'=>'Ajustes manuales de crédito'] as $key=>$label)<div class="col-md"><label class="form-label">{{ $label }}</label><input type="number" min="0" step="0.01" name="{{ $key }}" class="form-control" value="{{ $values[$key] ?? '0.00' }}"></div>@endforeach<div class="col-12"><label class="form-label">Notas</label><textarea name="notes" maxlength="5000" class="form-control">{{ $values['notes'] ?? '' }}</textarea></div></div></div><div class="card-footer d-flex justify-content-between align-items-center"><div><strong>IVA estimado por pagar: Q {{ number_format((float)$calculation['totals']['vat_payable'],2) }}</strong><br><span class="text-muted">Crédito para el siguiente período: Q {{ number_format((float)$calculation['totals']['credit_balance'],2) }}</span></div><button class="btn btn-primary"><i class="bi bi-save me-1"></i> Guardar borrador</button></div></form>

<div class="d-flex gap-2 mb-3"><a href="#includedDocuments" class="btn btn-outline-primary">Ver documentos incluidos</a><a href="#excludedDocuments" class="btn btn-outline-warning">Ver documentos excluidos</a></div>
@foreach([true=>'Documentos incluidos',false=>'Documentos excluidos'] as $included=>$title)<div class="card mb-4" id="{{ $included?'includedDocuments':'excludedDocuments' }}"><div class="card-header"><h2 class="h6 mb-0">{{ $title }}</h2></div><x-table-container><table class="table table-sm mb-0"><thead><tr><th>Fecha</th><th>Dirección</th><th>Tipo</th><th>Tercero</th><th>IVA</th><th>Total</th><th>Motivo</th></tr></thead><tbody>@forelse($calculation['documents']->where('included',(bool)$included) as $row)<tr><td>{{ data_get($row,'source_snapshot.document_date') }}</td><td>{{ $row['direction']==='PURCHASE'?'Compra':'Venta' }}</td><td>{{ $row['document_type_label'] }}</td><td>{{ data_get($row,'source_snapshot.third_party_name') }}</td><td>Q {{ number_format((float)$row['vat_amount'],2) }}</td><td>Q {{ number_format((float)$row['total_amount'],2) }}</td><td>{{ $row['exclusion_reason'] ?: '—' }}</td></tr>@empty<tr><td colspan="7">Sin documentos.</td></tr>@endforelse</tbody></table></x-table-container></div>@endforeach
@endsection
