@extends('layouts.app')
@section('title', 'Declaración de IVA '.$declaration->accountingPeriod->name)
@section('content')
<x-page-header title="Declaración de IVA" subtitle="{{ $company->name }} · {{ $declaration->accountingPeriod->name }}" icon="bi-percent"><x-slot:actions><a href="{{ route('vat-declarations.export.pdf',$declaration) }}" class="btn btn-outline-danger"><i class="bi bi-file-earmark-pdf"></i> PDF</a><a href="{{ route('vat-declarations.export.excel',$declaration) }}" class="btn btn-outline-success"><i class="bi bi-file-earmark-excel"></i> Excel</a><a href="{{ route('vat-declarations.index') }}" class="btn btn-outline-secondary">Volver</a></x-slot:actions></x-page-header>

@if($errors->any())<div class="alert alert-danger"><strong>No se pudo completar la acción:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($comparison['changed'])<div class="alert alert-warning"><strong>Los libros fiscales cambiaron después de preparar esta declaración.</strong><ul class="mb-0"><li>{{ $comparison['added'] }} documentos nuevos.</li><li>{{ $comparison['removed'] }} documentos retirados.</li><li>{{ $comparison['modified'] }} documentos modificados o con cambio de estado.</li><li>Diferencia estimada de IVA por pagar: Q {{ number_format((float)$comparison['vatDifference'],2) }}.</li></ul></div>@endif
@if($declaration->status->value !== 'FILED')<div class="alert alert-info">BORRADOR PARA REVISIÓN. No constituye constancia de presentación ante SAT.</div>@endif

<div class="card mb-4"><div class="card-body row g-3"><div class="col-md-3"><small class="text-muted">Empresa / NIT</small><div class="fw-semibold">{{ $company->legal_name ?: $company->name }}</div><div>{{ $company->tax_id }}</div></div><div class="col-md-3"><small class="text-muted">Período</small><div class="fw-semibold">{{ $declaration->accountingPeriod->name }}</div><div>{{ $declaration->accountingPeriod->start_date->format('d/m/Y') }} al {{ $declaration->accountingPeriod->end_date->format('d/m/Y') }}</div></div><div class="col-md-3"><small class="text-muted">Régimen</small><div class="fw-semibold">IVA General</div></div><div class="col-md-3"><small class="text-muted">Estado</small><div><span class="badge text-bg-primary">{{ $declaration->status->label() }}</span></div><small>Calculada {{ $declaration->calculated_at?->format('d/m/Y H:i') }}</small></div></div></div>

<div class="row g-3 mb-4">@foreach(['sales_vat_amount'=>'IVA ventas','purchase_vat_amount'=>'IVA compras','purchase_creditable_vat_amount'=>'IVA acreditable','purchase_non_creditable_vat_amount'=>'IVA no acreditable','net_vat_debit'=>'Débito neto','net_vat_credit'=>'Crédito neto','vat_payable'=>'IVA por pagar','credit_balance'=>'Crédito siguiente'] as $key=>$label)<div class="col-6 col-lg-3"><div class="card h-100"><div class="card-body"><small class="text-muted">{{ $label }}</small><div class="fs-5 fw-semibold">Q {{ number_format((float)$declaration->{$key},2) }}</div></div></div></div>@endforeach</div>

<div class="card mb-4"><div class="card-header"><h2 class="h6 mb-0">Acciones de estado</h2></div><div class="card-body d-flex flex-wrap gap-2">
@if($declaration->status->value==='DRAFT')<form method="POST" action="{{ route('vat-declarations.recalculate',$declaration) }}">@csrf<input type="hidden" name="accounting_period_id" value="{{ $declaration->accounting_period_id }}">@foreach(['previous_credit_balance','vat_withholdings','vat_perceptions','manual_debit_adjustments','manual_credit_adjustments','notes'] as $field)<input type="hidden" name="{{ $field }}" value="{{ $declaration->{$field} }}">@endforeach<button class="btn btn-outline-primary"><i class="bi bi-arrow-repeat"></i> Recalcular desde libros</button></form><form method="POST" action="{{ route('vat-declarations.review',$declaration) }}">@csrf<button class="btn btn-primary">Marcar revisada</button></form>@endif
@if($declaration->status->value==='REVIEWED')<form method="POST" action="{{ route('vat-declarations.ready',$declaration) }}">@csrf<button class="btn btn-success">Marcar lista para presentar</button></form>@endif
@if(in_array($declaration->status->value,['REVIEWED','READY_TO_FILE']))<form method="POST" action="{{ route('vat-declarations.draft',$declaration) }}">@csrf<button class="btn btn-outline-warning">Devolver a borrador</button></form>@endif
</div></div>

@if($declaration->status->value==='READY_TO_FILE')<form method="POST" action="{{ route('vat-declarations.file',$declaration) }}" class="card mb-4">@csrf<div class="card-header"><h2 class="h6 mb-0">Registrar presentación manual ante SAT</h2></div><div class="card-body"><div class="alert alert-warning">Esta acción solo registra datos ingresados por el usuario. El sistema no enviará información a SAT.</div><div class="row g-3"><div class="col-md-3"><label class="form-label">Fecha de presentación</label><input type="datetime-local" name="filed_at" class="form-control" required></div><div class="col-md-3"><label class="form-label">Número de formulario</label><input name="sat_form_number" class="form-control" required></div><div class="col-md-3"><label class="form-label">Número de acceso</label><input name="sat_access_number" class="form-control" required></div><div class="col-md-3"><label class="form-label">Boleta SAT-2000</label><input name="sat_payment_slip_number" class="form-control"></div><div class="col-md-3"><label class="form-label">Monto pagado</label><input type="number" min="0" step="0.01" name="amount_paid" value="{{ $declaration->vat_payable }}" class="form-control" required></div><div class="col-md-9"><label class="form-label">Observaciones</label><textarea name="notes" class="form-control" maxlength="5000">{{ $declaration->notes }}</textarea></div></div></div><div class="card-footer"><button class="btn btn-success" onclick="return confirm('¿Registrar que esta declaración fue presentada manualmente?')">Registrar presentación</button></div></form>@endif

@foreach([true=>'Documentos incluidos en el snapshot',false=>'Documentos excluidos y advertencias'] as $included=>$title)<div class="card mb-4"><div class="card-header"><h2 class="h6 mb-0">{{ $title }} · {{ $declaration->documents->where('included',(bool)$included)->count() }}</h2></div><x-table-container><table class="table table-sm mb-0"><thead><tr><th>Fecha</th><th>Dirección</th><th>Tipo</th><th>Tercero</th><th>Revisión</th><th>Fiscal</th><th>IVA</th><th>Total</th><th>Motivo</th></tr></thead><tbody>@forelse($declaration->documents->where('included',(bool)$included) as $snapshot)@php($source=$snapshot->source_snapshot??[])<tr><td>{{ $source['document_date']??'—' }}</td><td>{{ $snapshot->direction->label() }}</td><td>{{ $snapshot->document_type->label() }}</td><td>{{ $source['third_party_name']??'—' }}</td><td>{{ $snapshot->review_status }}</td><td>{{ $snapshot->fiscal_status->value }}</td><td>Q {{ number_format((float)$snapshot->vat_amount,2) }}</td><td>Q {{ number_format((float)$snapshot->total_amount,2) }}</td><td>{{ $snapshot->exclusion_reason??'—' }}</td></tr>@empty<tr><td colspan="9">Sin documentos.</td></tr>@endforelse</tbody></table></x-table-container></div>@endforeach
@endsection
